# Generated by Django 5.1.7 on 2025-03-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='answer',
        ),
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.TextField(default='default_text'),
            preserve_default=False,
        ),
    ]
