# Generated by Django 5.1.7 on 2025-03-18 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_rename_text_question_answer_question_question'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('topic', 'question')},
        ),
    ]
